--娜娜的室友
require("/expansions/script/c37564765")
require("/expansions/script/c37564777")
function c66623302.initial_effect(c)
	senya.setreg(c,66623302,66623300)
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(66623302,0))
	e1:SetCategory(CATEGORY_DRAW)
	e1:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_O)
	e1:SetProperty(EFFECT_FLAG_DELAY+EFFECT_FLAG_DAMAGE_STEP)
	e1:SetRange(LOCATION_HAND)
	e1:SetCode(EVENT_SUMMON_SUCCESS)
	e1:SetLabel(1)
	e1:SetCost(senya.serlcost)
	e1:SetCondition(function(e,tp,eg,ep,ev,re,r,rp)
		return eg and eg:IsExists(c66623302.sfilter,1,nil,tp,e:GetLabel())
	end)
	e1:SetTarget(senya.drawtg(1))
	e1:SetOperation(senya.drawop)
	c:RegisterEffect(e1)
	local e2=e1:Clone()
	e2:SetCode(EVENT_SPSUMMON_SUCCESS)
	e2:SetLabel(2)
	c:RegisterEffect(e2)
	local e3=e1:Clone()
	e3:SetDescription(aux.Stringid(66623302,1))
	e3:SetCategory(CATEGORY_SPECIAL_SUMMON)
	e3:SetRange(LOCATION_GRAVE)
	e3:SetCost(prim.szcost)
	e3:SetCondition(function(e,tp,eg,ep,ev,re,r,rp)
		return eg and eg:IsExists(c66623302.sfilter,1,nil,tp,e:GetLabel()) and aux.exccon(e)
	end)
	e3:SetTarget(senya.swwsstg)
	e3:SetOperation(senya.swwssop)
	c:RegisterEffect(e3)
	local e4=e3:Clone()
	e4:SetCode(EVENT_SPSUMMON_SUCCESS)
	e4:SetLabel(2)
	c:RegisterEffect(e4)
end
function c66623302.sfilter(c,tp,l)
	local ty=c:GetSummonType()
	return (bit.band(c:GetSummonType(),SUMMON_TYPE_RITUAL)==SUMMON_TYPE_RITUAL or l==1) and c:IsHasEffect(66623300) and c:GetSummonPlayer()==tp
end