--ＳＧａｒ（ステラライズ・ガーデヴォイアー）・ドーンブレイク
function c9991014.initial_effect(c)
	--Xyz
	aux.AddXyzProcedure(c,nil,5,3)
	c:EnableReviveLimit()
	--Cannot Activate
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_CONTINUOUS)
	e1:SetCode(EVENT_SPSUMMON_SUCCESS)
	e1:SetOperation(function(e,tp,eg,ep,ev,re,r,rp)
		local ph=Duel.GetCurrentPhase()
		if bit.band(ph,0xf8)~=0 then ph=PHASE_BATTLE end
		local e1=Effect.CreateEffect(e:GetHandler())
		e1:SetType(EFFECT_TYPE_FIELD)
		e1:SetCode(EFFECT_CANNOT_ACTIVATE)
		e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
		e1:SetTargetRange(0,1)
		e1:SetValue(1)
		e1:SetReset(RESET_PHASE+ph)
		Duel.RegisterEffect(e1,tp)
	end)
	c:RegisterEffect(e1)
	--Summon Success
	local e2=Effect.CreateEffect(c)
	e2:SetDescription(aux.Stringid(9991014,0))
	e2:SetCategory(CATEGORY_TOGRAVE)
	e2:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_TRIGGER_O)
	e2:SetProperty(EFFECT_FLAG_DAMAGE_STEP+EFFECT_FLAG_DELAY)
	e2:SetCode(EVENT_SPSUMMON_SUCCESS)
	e2:SetCountLimit(1,EFFECT_COUNT_CODE_SINGLE)
	e2:SetCost(function(e,tp,eg,ep,ev,re,r,rp,chk)
		if chk==0 then return e:GetHandler():CheckRemoveOverlayCard(tp,1,REASON_COST) end
		e:GetHandler():RemoveOverlayCard(tp,1,1,REASON_COST)
	end)
	e2:SetTarget(function(e,tp,eg,ep,ev,re,r,rp,chk)
		if chk==0 then return Duel.IsExistingMatchingCard(aux.TRUE,tp,0,LOCATION_ONFIELD,1,nil) end
		local sg=Duel.GetMatchingGroup(aux.TRUE,tp,0,LOCATION_ONFIELD,nil)
		Duel.SetOperationInfo(0,CATEGORY_TOGRAVE,sg,1,0,0)
	end)
	e2:SetOperation(function(e,tp,eg,ep,ev,re,r,rp)
		local sg=Duel.GetFieldGroup(tp,0,LOCATION_ONFIELD)
		if sg:GetCount()==0 then return end
		local cg=sg:Filter(Card.IsFacedown,nil)
		if cg:GetCount()~=0 then
			Duel.ConfirmCards(cg,tp)
		end
		local t={TYPE_MONSTER,TYPE_SPELL,TYPE_TRAP}
		local g=Group.CreateGroup()
		for i,typ in pairs(t) do
			Duel.Hint(HINT_SELECTMSG,1-tp,aux.Stringid(9991014,i+1))
			local g1=sg:FilterSelect(1-tp,Card.IsType,1,1,nil,typ)
			g:Merge(g1)
			sg:Sub(g1)
		end
		Duel.HintSelection(g)
		Duel.SendtoGrave(g,REASON_RULE)
		g:ForEach(function(tc)
			local code=tc:GetCode()
			local e1=Effect.GlobalEffect()
			e1:SetType(EFFECT_TYPE_FIELD)
			e1:SetCode(EFFECT_CANNOT_SUMMON)
			e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
			e1:SetTargetRange(1,1)
			e1:SetLabel(code)
			e1:SetTarget(function(e,c,tp,sumtp,sumpos)
				return c:IsCode(e:GetLabel())
			end)
			Duel.RegisterEffect(e1,tp)
			local e2=e1:Clone()
			e2:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
			e2:SetLabelObject(e1)
			Duel.RegisterEffect(e2,tp)
			local e3=e1:Clone()
			e3:SetCode(EFFECT_CANNOT_TRIGGER)
			e3:SetProperty(EFFECT_FLAG_SET_AVAILABLE+EFFECT_FLAG_IGNORE_RANGE)
			e3:SetTargetRange(0xff,0xff)
			e3:SetLabelObject(e2)
			Duel.RegisterEffect(e3,tp)
			local e4=Effect.GlobalEffect()
			e4:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
			e4:SetCode(EVENT_PHASE_START+PHASE_DRAW)
			e4:SetLabelObject(e3)
			e4:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
			e4:SetCondition(function(e,tp)
				return Duel.GetTurnPlayer()==tp
			end)
			e4:SetOperation(function(e)
				e:GetLabelObject():GetLabelObject():GetLabelObject():Reset()
				e:GetLabelObject():GetLabelObject():Reset()
				e:GetLabelObject():Reset()
				e:Reset()
			end)
			Duel.RegisterEffect(e4,tp)
		end)
	end)
	c:RegisterEffect(e2)
	--Standby Phase
	local e3=e2:Clone()
	e3:SetDescription(aux.Stringid(9991014,1))
	e3:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_TRIGGER_O)
	e3:SetCode(EVENT_PHASE+PHASE_STANDBY)
	e3:SetRange(LOCATION_MZONE)
	e3:SetCountLimit(1,EFFECT_COUNT_CODE_SINGLE)
	e3:SetCondition(function(e,tp,eg,ep,ev,re,r,rp)
		return Duel.GetTurnPlayer()==tp
	end)
	c:RegisterEffect(e3)
end
c9991014.Dazz_name_stellaris="Gardevoir"
