--ステラライズ・アジュディケーター
function c9991021.initial_effect(c)
	--Xyz
	aux.AddXyzProcedure(c,nil,12,3)
	c:EnableReviveLimit()
	local ex1=Effect.CreateEffect(c)
	ex1:SetType(EFFECT_TYPE_SINGLE)
	ex1:SetCode(EFFECT_CANNOT_DISABLE_SPSUMMON)
	c:RegisterEffect(ex1)
	local ex2=ex1:Clone()
	ex2:SetProperty(EFFECT_FLAG_CANNOT_DISABLE+EFFECT_FLAG_UNCOPYABLE)
	ex2:SetCode(EFFECT_SPSUMMON_CONDITION)
	ex2:SetValue(aux.FALSE)
	c:RegisterEffect(ex2)
	--Weifeng Yaoguai
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_SINGLE)
	e1:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e1:SetRange(LOCATION_MZONE)
	e1:SetCode(EFFECT_CANNOT_BE_EFFECT_TARGET)
	e1:SetValue(aux.tgoval)
	c:RegisterEffect(e1)
	local e2=Effect.CreateEffect(c)
	e2:SetType(EFFECT_TYPE_SINGLE)
	e2:SetProperty(EFFECT_FLAG_SINGLE_RANGE)
	e2:SetCode(EFFECT_INDESTRUCTABLE_EFFECT)
	e2:SetRange(LOCATION_MZONE)
	e2:SetValue(function(e,re,tp)
		return tp~=e:GetHandlerPlayer()
	end)
	c:RegisterEffect(e2)
	--Attack Death
	local e3=Effect.CreateEffect(c)
	e3:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e3:SetCode(EVENT_ATTACK_ANNOUNCE)
	e3:SetRange(LOCATION_MZONE)
	e3:SetCondition(function(e,tp,eg,ep,ev,re,r,rp)
		return Duel.GetAttacker():IsControler(1-tp)
	end)
	e3:SetOperation(function(e,tp,eg,ep,ev,re,r,rp)
		local tc=Duel.GetAttacker()
		Duel.HintSelection(Group.FromCards(tc))
		Duel.SendtoGrave(tc,REASON_RULE)
		local code=tc:GetCode()
		local e1=Effect.GlobalEffect()
		e1:SetType(EFFECT_TYPE_FIELD)
		e1:SetCode(EFFECT_CANNOT_SUMMON)
		e1:SetProperty(EFFECT_FLAG_PLAYER_TARGET)
		e1:SetTargetRange(1,1)
		e1:SetLabel(code)
		e1:SetTarget(function(e,c,tp,sumtp,sumpos)
			return c:IsCode(e:GetLabel())
		end)
		Duel.RegisterEffect(e1,tp)
		local e2=e1:Clone()
		e2:SetCode(EFFECT_CANNOT_SPECIAL_SUMMON)
		e2:SetLabelObject(e1)
		Duel.RegisterEffect(e2,tp)
		local e3=e1:Clone()
		e3:SetCode(EFFECT_CANNOT_TRIGGER)
		e3:SetProperty(EFFECT_FLAG_SET_AVAILABLE+EFFECT_FLAG_IGNORE_RANGE)
		e3:SetTargetRange(0xff,0xff)
		e3:SetLabelObject(e2)
		Duel.RegisterEffect(e3,tp)
		local e4=Effect.GlobalEffect()
		e4:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
		e4:SetCode(EVENT_PHASE_START+PHASE_DRAW)
		e4:SetLabelObject(e3)
		e4:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
		e4:SetCondition(function(e,tp)
			return Duel.GetTurnPlayer()==tp
		end)
		e4:SetOperation(function(e)
			e:GetLabelObject():GetLabelObject():GetLabelObject():Reset()
			e:GetLabelObject():GetLabelObject():Reset()
			e:GetLabelObject():Reset()
			e:Reset()
		end)
		Duel.RegisterEffect(e4,tp)
	end)
	c:RegisterEffect(e3)
end
c9991021Dazz_name_stellaris=true
